version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: db_entrega2
    ports:
      - "5432:5432"
  
  frontback:
    build:
      context: .
      dockerfile: frontback/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
