version: '3.1'

services:

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: db_entrega4
    ports:
      - 5432:5432
    container_name: meu-db
  # app:
  #   build: ./flask
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   container_name: meu-app
