version: '3.1'

services:

  db:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: db_entrega4
    ports:
      - 5432:5432
    container_name: meu-db

  app:
    build: ./backend
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
    container_name: meu-app
